# Generated by Django 6.0.5 on 2026-06-03 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedocument',
            name='document_file',
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('PASSPORT', 'Passport'), ('VISA', 'Visa'), ('EMIRATES_ID', 'Emirates ID'), ('LABOUR_CARD', 'Labour Card'), ('CONTRACT', 'Contract / Offer Letter')], max_length=30),
        ),
        migrations.CreateModel(
            name='EmployeeDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='employee_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='employees.employeedocument')),
            ],
        ),
    ]
