# Generated by Django 6.0.5 on 2026-06-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employeedocument_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('PASSPORT', 'Passport'), ('VISA', 'Visa'), ('EMIRATES_ID', 'Emirates ID'), ('LABOUR_CARD', 'Labour Card'), ('CONTRACT', 'Contract / Offer Letter'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
