# Generated by Django 6.0.5 on 2026-06-11 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_alter_monthlytimesheet_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTimesheetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('day_1', models.CharField(blank=True, max_length=10)),
                ('day_2', models.CharField(blank=True, max_length=10)),
                ('day_3', models.CharField(blank=True, max_length=10)),
                ('day_4', models.CharField(blank=True, max_length=10)),
                ('day_5', models.CharField(blank=True, max_length=10)),
                ('day_6', models.CharField(blank=True, max_length=10)),
                ('day_7', models.CharField(blank=True, max_length=10)),
                ('day_8', models.CharField(blank=True, max_length=10)),
                ('day_9', models.CharField(blank=True, max_length=10)),
                ('day_10', models.CharField(blank=True, max_length=10)),
                ('day_11', models.CharField(blank=True, max_length=10)),
                ('day_12', models.CharField(blank=True, max_length=10)),
                ('day_13', models.CharField(blank=True, max_length=10)),
                ('day_14', models.CharField(blank=True, max_length=10)),
                ('day_15', models.CharField(blank=True, max_length=10)),
                ('day_16', models.CharField(blank=True, max_length=10)),
                ('day_17', models.CharField(blank=True, max_length=10)),
                ('day_18', models.CharField(blank=True, max_length=10)),
                ('day_19', models.CharField(blank=True, max_length=10)),
                ('day_20', models.CharField(blank=True, max_length=10)),
                ('day_21', models.CharField(blank=True, max_length=10)),
                ('day_22', models.CharField(blank=True, max_length=10)),
                ('day_23', models.CharField(blank=True, max_length=10)),
                ('day_24', models.CharField(blank=True, max_length=10)),
                ('day_25', models.CharField(blank=True, max_length=10)),
                ('day_26', models.CharField(blank=True, max_length=10)),
                ('day_27', models.CharField(blank=True, max_length=10)),
                ('day_28', models.CharField(blank=True, max_length=10)),
                ('day_29', models.CharField(blank=True, max_length=10)),
                ('day_30', models.CharField(blank=True, max_length=10)),
                ('day_31', models.CharField(blank=True, max_length=10)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='timesheet.monthlytimesheet')),
            ],
        ),
    ]
