# Generated by Django 6.0.5 on 2026-06-18 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_joining_date_and_more'),
        ('timesheet', '0003_monthlytimesheetrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytimesheetrow',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employee'),
        ),
    ]
