# Generated by Django 6.0.5 on 2026-06-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsite',
            name='lpo_file',
            field=models.FileField(blank=True, null=True, upload_to='project_sites/lpo/'),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='quotation_file',
            field=models.FileField(blank=True, null=True, upload_to='project_sites/quotations/'),
        ),
    ]
