# Generated by Django 6.0.5 on 2026-06-08 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_employeeassignment'),
        ('employees', '0003_alter_employee_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassignment',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.designation'),
        ),
    ]
