# Generated by Django 6.0.5 on 2026-06-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_employeeassignment_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsite',
            name='lpo_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
