# Generated by Django 6.0.5 on 2026-06-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='po_box',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
