# Generated by Django 6.0.5 on 2026-06-18 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_po_box'),
        ('employees', '0003_alter_employee_joining_date_and_more'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='salary_type',
            field=models.CharField(default='HOURLY', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'month', 'year')},
        ),
    ]
