# Generated by Django 6.0.5 on 2026-06-19 12:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_po_box'),
        ('payroll', '0006_payroll_reopen_reason_payroll_reopened_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveSmallIntegerField()),
                ('payment_method', models.CharField(choices=[('WPS', 'WPS'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], max_length=10)),
                ('payment_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('REVERSED', 'Reversed')], default='COMPLETED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payment_batches', to='companies.company')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_payroll_batches', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_payroll_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-payment_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PayrollPaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='payroll.payrollpaymentbatch')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_items', to='payroll.payroll')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'payroll'), name='unique_payroll_in_payment_batch')],
            },
        ),
    ]
