# Generated by Django 6.0.5 on 2026-06-13 15:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_employeeassignment_designation'),
        ('employees', '0003_alter_employee_joining_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBillingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('billing_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.designation')),
                ('project_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.projectsite')),
            ],
            options={
                'unique_together': {('project_site', 'billing_designation')},
            },
        ),
    ]
