# Generated by Django 6.0.5 on 2026-06-13 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice'),
        ('timesheet', '0003_monthlytimesheetrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='month',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='project_site',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='year',
        ),
        migrations.AddField(
            model_name='invoice',
            name='timesheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='timesheet.monthlytimesheet'),
        ),
    ]
