# Generated by Django 6.0.5 on 2026-06-15 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoiceitem'),
        ('timesheet', '0003_monthlytimesheetrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='timesheet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='timesheet.monthlytimesheet'),
        ),
    ]
