# Generated by Django 6.0.5 on 2026-06-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoice_approved_by_invoice_approved_by_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='lpo_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
