# Generated by Django 6.0.5 on 2026-06-09 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_employeeassignment_designation'),
        ('employees', '0003_alter_employee_joining_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave'), ('HOLIDAY', 'Holiday')], default='PRESENT', max_length=20)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='clients.employeeassignment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
                ('project_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='clients.projectsite')),
            ],
            options={
                'unique_together': {('attendance_date', 'project_site', 'employee')},
            },
        ),
    ]
